<Project>
  <ItemGroup>
    <CompilerVisibleProperty Include="CompilerGeneratedFilesOutputPath" />
    <CompilerVisibleProperty Include="EmitCompilerGeneratedFiles" />
    <CompilerVisibleProperty Include="BaseIntermediateOutputPath" />
    <CompilerVisibleProperty Include="BaseOutputPath" />
  </ItemGroup>
</Project>
