<Project>
  <ItemGroup>
    <CompilerVisibleProperty Include="CompilerGeneratedFilesOutputPath" />
    <CompilerVisibleProperty Include="EmitCompilerGeneratedFiles" />
    <CompilerVisibleProperty Include="BaseIntermediateOutputPath" />
    <CompilerVisibleProperty Include="BaseOutputPath" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GoLive.Generator.RazorPageRoute.Generator.Tests" />
  </ItemGroup>
</Project>
