using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GoLive.Generator.RazorPageRoute.Generator.Experimental;

[Generator]
public class BlazorRouteDiscoveryGenerator : IIncrementalGenerator
{
    private const string DiagnosticCategory = "BlazorRouteDiscovery";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("ExcludeFromRouteGenerationAttribute.g.cs",
                "// <auto-generated/>\n" +
                "#pragma warning disable CS1591\n" +
                "namespace GoLive.Generator.RazorPageRoute.Generator.Experimental;\n" +
                "[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]\n" +
                "public sealed class ExcludeFromRouteGenerationAttribute : global::System.Attribute { }\n");
        });

        var configProvider = context.AdditionalTextsProvider
            .Where(static t => t.Path.EndsWith("RazorPageRoutes.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, ct) =>
            {
                var content = text.GetText(ct)?.ToString();
                return (Path: text.Path, Content: content);
            })
            .Where(static t => t.Content != null);

        var optionsProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, ct) =>
            {
                options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
                options.GlobalOptions.TryGetValue("build_property.BaseIntermediateOutputPath", out var basePath);
                return new GeneratorOptions(rootNamespace ?? "DefaultNamespace", basePath ?? "");
            });

        var razorFileContents = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) =>
            {
                var content = file.GetText(ct)?.ToString();
                return (Path: file.Path, Content: content ?? string.Empty);
            })
            .Collect();

        var combined = configProvider
            .Combine(optionsProvider)
            .Combine(razorFileContents)
            .Combine(context.CompilationProvider)
            .Select(static (pair, ct) =>
            {
                var (((config, genOptions), razorFiles), compilation) = pair;
                var settings = ParseSettings(config.Path!, config.Content!, genOptions.RootNamespace);
                if (settings == null) return default(GenerationResult?);

                var cachePath = string.IsNullOrEmpty(genOptions.BaseIntermediateOutputPath)
                    ? null
                    : Path.Combine(genOptions.BaseIntermediateOutputPath, "route-cache.json");

                var oldMethodMap = cachePath != null ? ReadRouteCache(cachePath) : [];

                var projectDir = Path.GetDirectoryName(config.Path!) ?? "";
                var (routes, duplicates) = DiscoverRoutes(razorFiles, settings, compilation, projectDir, genOptions.RootNamespace);

                var renamedRoutes = new List<(string Route, string OldMethod, string NewMethod)>();
                if (oldMethodMap.Count > 0)
                {
                    var currentMap = routes.ToDictionary(
                        r => r.Route,
                        r => ComputeFullSlug(r, settings));

                    foreach (var kvp in currentMap)
                    {
                        if (oldMethodMap.TryGetValue(kvp.Key, out var oldMethod) && oldMethod != kvp.Value)
                        {
                            renamedRoutes.Add((kvp.Key, oldMethod, kvp.Value));
                        }
                    }
                }

                return new GenerationResult(settings, routes, duplicates, renamedRoutes, cachePath);
            })
            .Where(static r => r != null);

        context.RegisterSourceOutput(combined, static (spc, result) =>
        {
            var (settings, routes, duplicates, renamedRoutes, cachePath) = result!.Value;

            // Sort routes by URL for deterministic output order
            routes.Sort(static (a, b) => string.Compare(a.Route, b.Route, StringComparison.Ordinal));

            if (settings.EnableDuplicateRouteWarning)
            {
                foreach (var (route, fileNames) in duplicates)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("BRD003", "Duplicate route",
                            "Route '{0}' is declared in multiple components: {1}. Only the first will be generated.",
                            DiagnosticCategory, DiagnosticSeverity.Warning, true),
                        Location.None, route, string.Join(", ", fileNames)));
                }
            }

            foreach (var (route, oldMethod, newMethod) in renamedRoutes)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("BRD004", "Route method renamed",
                        "Route '{0}' was previously mapped to method '{1}' but is now mapped to '{2}'. Update call sites from PageRoutes.{1}() to PageRoutes.{2}().",
                        DiagnosticCategory, DiagnosticSeverity.Warning, true),
                    Location.None, route, oldMethod, newMethod));
            }

            var source = BuildSource(settings, routes);
            if (!string.IsNullOrWhiteSpace(source))
            {
                if (settings.OutputToFiles.Count > 0)
                {
                    foreach (var outputPath in settings.OutputToFiles)
                    {
                        try { File.WriteAllText(outputPath, source); } catch { }
                    }
                }
                else
                {
                    spc.AddSource($"{settings.ClassName}.g.cs", source);
                }
            }

            if (cachePath != null)
            {
                WriteRouteCache(cachePath, routes, settings);
            }

            if (settings.JsonRepresentation.Count > 0 && routes.Count > 0)
            {
                var jsonPayload = routes.Select(r => new
                {
                    r.Name,
                    r.Route,
                    QueryString = r.QueryString?.Select(q => new { q.Name, q.Type }),
                    Auth = r.Auth == null ? null : new
                    {
                        r.Auth.RequiresAuthentication,
                        r.Auth.Roles,
                        r.Auth.Policies,
                        r.Auth.AuthenticationSchemes,
                        CustomAuth = r.Auth.CustomAuth?.Select(c => new
                        {
                            c.Name,
                            c.CtorParams,
                            c.NamedParams
                        })
                    },
                    Invokables = r.Invokables?.Select(i => new { i.MethodName, i.InvokableName }),
                    RouteParams = r.RouteParams?.Select(p => new { p.Name, p.Type, p.HasParameterAttr, p.Constraint }),
                    Validations = r.Validations?.Select(v => new { v.PropertyName, v.RuleType, v.Param, v.Message })
                }).ToList();

                var json = JsonSerializer.Serialize(jsonPayload, new JsonSerializerOptions { WriteIndented = true });
                foreach (var jsonPath in settings.JsonRepresentation)
                {
                    try { File.WriteAllText(jsonPath, json); } catch { }
                }
            }

            if (settings.GenerateHttpFile && !string.IsNullOrEmpty(settings.HttpFileOutput))
            {
                try
                {
                    var httpContent = GenerateHttpFile(routes);
                    File.WriteAllText(settings.HttpFileOutput, httpContent);
                }
                catch { }
            }

            if (settings.Invokables.Enabled && routes.Any(r => r.Invokables?.Count > 0))
            {
                GenerateJSInvokable(settings, routes);
            }
        });
    }

    private static Settings? ParseSettings(string configPath, string configContent, string rootNamespace)
    {
        var config = JsonSerializer.Deserialize<Settings>(configContent);
        if (config == null) return null;

        if (string.IsNullOrEmpty(config.Namespace))
            config.Namespace = rootNamespace;

        var configFileDirectory = Path.GetDirectoryName(configPath);

        if (config.OutputToFiles != null && config.OutputToFiles.Count > 0)
        {
            config.OutputToFiles = config.OutputToFiles.Select(r =>
                Path.GetFullPath(Path.Combine(configFileDirectory!, r))).ToList();
        }

        if (config.JsonRepresentation != null && config.JsonRepresentation.Count > 0)
        {
            config.JsonRepresentation = config.JsonRepresentation.Select(r =>
                Path.GetFullPath(Path.Combine(configFileDirectory!, r))).ToList();
        }

        if (config.Invokables != null && config.Invokables.OutputToFiles.Count > 0)
        {
            for (int i = 0; i < config.Invokables.OutputToFiles.Count; i++)
            {
                config.Invokables.OutputToFiles[i] =
                    Path.GetFullPath(Path.Combine(configFileDirectory!, config.Invokables.OutputToFiles[i]));
            }
        }

        if (config.GenerateHttpFile && !string.IsNullOrEmpty(config.HttpFileOutput))
        {
            config.HttpFileOutput = Path.GetFullPath(Path.Combine(configFileDirectory!, config.HttpFileOutput));
        }

        return config;
    }

    private static (List<PageRoute> Routes, List<(string Route, List<string> FileNames)> Duplicates) DiscoverRoutes(
        ImmutableArray<(string Path, string Content)> razorFiles,
        Settings settings,
        Compilation compilation,
        string projectDir,
        string rootNamespace)
    {
        var result = new List<PageRoute>();
        var routeFileMap = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
        var excludeRegex = !string.IsNullOrEmpty(settings.ExcludePattern)
            ? new Regex(settings.ExcludePattern, RegexOptions.IgnoreCase)
            : null;

        foreach (var (filePath, content) in razorFiles)
        {
            var parsed = RazorFileParser.Parse(filePath, content);

            // F15: Exclude support
            if (parsed.Excluded) continue;
            if (excludeRegex != null && excludeRegex.IsMatch(filePath)) continue;

            if (parsed.Routes.Length == 0) continue;

            var auth = ExtractAuthFromAttributes(parsed.Attributes, settings, compilation);
            var queryParams = ExtractQueryParams(parsed.Members);
            var invokables = ExtractInvokables(parsed.Members, filePath);

            foreach (var route in parsed.Routes)
            {
                var name = Path.GetFileNameWithoutExtension(filePath);
                var routeTemplate = Routing.TemplateParser.ParseTemplate(route);
                var routeParams = ExtractRouteParams(parsed.Members, routeTemplate);

                var fullTypeName = ComputeFullTypeName(filePath, projectDir, rootNamespace, name);

                result.Add(new PageRoute(
                    name,
                    route,
                    queryParams ?? [],
                    auth,
                    invokables ?? [],
                    routeParams,
                    []) { FullTypeName = fullTypeName });

                if (!routeFileMap.ContainsKey(route))
                    routeFileMap[route] = new List<string>();
                routeFileMap[route].Add(name);
            }
        }

        var duplicates = routeFileMap
            .Where(kvp => kvp.Value.Count > 1)
            .Select(kvp => (kvp.Key, kvp.Value))
            .ToList();

        result = result.GroupBy(r => r.Route, StringComparer.OrdinalIgnoreCase)
            .Select(g => g.First())
            .ToList();

        return (result, duplicates);
    }

    private static string ComputeFullTypeName(string filePath, string projectDir, string rootNamespace, string className)
    {
        var dir = Path.GetDirectoryName(filePath) ?? "";
        if (dir.StartsWith(projectDir, StringComparison.OrdinalIgnoreCase))
        {
            var relativeDir = dir.Substring(projectDir.Length).TrimStart('\\', '/');
            if (!string.IsNullOrEmpty(relativeDir))
            {
                var nsSuffix = relativeDir.Replace('\\', '.').Replace('/', '.');
                return $"{rootNamespace}.{nsSuffix}.{className}";
            }
        }
        return $"{rootNamespace}.{className}";
    }

    private static List<RouteParameterInfo>? ExtractRouteParams(ImmutableArray<CodeMember> members, Routing.RouteTemplate routeTemplate)
    {
        var paramSegments = routeTemplate.Segments.Where(s => s.IsParameter).ToList();
        if (paramSegments.Count == 0) return null;

        var routeParams = new List<RouteParameterInfo>();

        foreach (var segment in paramSegments)
        {
            var constraint = segment.Constraints.Any()
                ? segment.Constraints.FirstOrDefault().GetConstraintType()
                : null;

            var constraintType = constraint != null ? constraint.FullName : null;
            var paramType = constraintType ?? "string";

            // F3: Check if any code member has [Parameter] with matching name
            var hasParameterAttr = false;
            foreach (var member in members)
            {
                if (member.Kind is "property" or "field" &&
                    member.Name.Equals(segment.Value, StringComparison.OrdinalIgnoreCase) &&
                    member.AttributeNames.Any(a => a is "Parameter" or "ParameterAttribute"
                        || a.EndsWith(".Parameter") || a.EndsWith(".ParameterAttribute")))
                {
                    hasParameterAttr = true;
                    paramType = member.TypeName;
                    break;
                }
            }

            routeParams.Add(new RouteParameterInfo(segment.Value, paramType, hasParameterAttr, constraintType));
        }

        return routeParams;
    }

    private static PageRouteAuth? ExtractAuthFromAttributes(
        ImmutableArray<RazorAttribute> attributes,
        Settings settings,
        Compilation compilation)
    {
        var auth = new PageRouteAuth();
        var compilationUsings = GetCompilationUsings(compilation);

        foreach (var attr in attributes)
        {
            var parsedAttr = ParseAttributeText(attr.Text);
            if (parsedAttr == null) continue;

            var attrName = parsedAttr.Name.ToString();

            if (IsAuthorizeAttribute(attrName))
            {
                auth.RequiresAuthentication = true;
                ExtractAuthorizeArguments(parsedAttr, auth, compilation, compilationUsings);
            }
            else
            {
                TryExtractCustomAuth(parsedAttr, settings, auth, compilation, compilationUsings);
            }
        }

        return auth.RequiresAuthentication ? auth : null;
    }

    private static AttributeSyntax? ParseAttributeText(string attributeText)
    {
        var code = $"class _X {{ [{attributeText}] void _Y() {{ }} }}";
        SyntaxTree tree;
        try
        {
            tree = CSharpSyntaxTree.ParseText(code, new CSharpParseOptions(LanguageVersion.Latest));
        }
        catch
        {
            return null;
        }

        var root = tree.GetRoot();
        return root.DescendantNodes().OfType<AttributeSyntax>().FirstOrDefault();
    }

    private static bool IsAuthorizeAttribute(string name)
    {
        return name is "Authorize" or "AuthorizeAttribute"
            || name == "Microsoft.AspNetCore.Authorization.AuthorizeAttribute"
            || name.EndsWith(".AuthorizeAttribute");
    }

    private static void ExtractAuthorizeArguments(
        AttributeSyntax attr,
        PageRouteAuth auth,
        Compilation compilation,
        List<string> compilationUsings)
    {
        if (attr.ArgumentList == null) return;

        foreach (var arg in attr.ArgumentList.Arguments)
        {
            if (arg.NameEquals != null)
            {
                var argName = arg.NameEquals.Name.Identifier.Text;
                var value = GetAttributeArgumentValue(arg, compilation, compilationUsings);

                switch (argName)
                {
                    case "Roles":
                        auth.Roles = value.Split(',').Select(r => r.Trim()).ToList();
                        break;
                    case "Policy":
                        auth.Policies = value.Split(',').Select(p => p.Trim()).ToList();
                        break;
                    case "AuthenticationSchemes":
                        auth.AuthenticationSchemes = value.Split(',').Select(s => s.Trim()).ToList();
                        break;
                }
            }
            else
            {
                var value = GetAttributeArgumentValue(arg, compilation, compilationUsings);
                if (!string.IsNullOrEmpty(value))
                {
                    auth.Roles = value.Split(',').Select(r => r.Trim()).ToList();
                }
            }
        }
    }

    private static void TryExtractCustomAuth(
        AttributeSyntax attr,
        Settings settings,
        PageRouteAuth auth,
        Compilation compilation,
        List<string> compilationUsings)
    {
        if (settings.Auth == null) return;

        var attrName = attr.Name.ToString();
        foreach (var customAuth in settings.Auth)
        {
            if (customAuth.Attribute == null) continue;
            if (!customAuth.Attribute.Any(a => a == attrName || a.EndsWith("." + attrName))) continue;

            auth.RequiresAuthentication = true;

            var ctorArgs = new Dictionary<string, string>();
            var namedArgs = new Dictionary<string, string>();

            if (attr.ArgumentList != null)
            {
                for (int i = 0; i < attr.ArgumentList.Arguments.Count; i++)
                {
                    var arg = attr.ArgumentList.Arguments[i];
                    if (arg.NameEquals != null)
                    {
                        namedArgs[arg.NameEquals.Name.Identifier.Text] = GetAttributeArgumentValue(arg, compilation, compilationUsings);
                    }
                    else
                    {
                        ctorArgs[$"arg{i}"] = GetAttributeArgumentValue(arg, compilation, compilationUsings);
                    }
                }
            }

            auth.CustomAuth ??= new List<PageRouteAuthCustomAuth>();
            auth.CustomAuth.Add(new PageRouteAuthCustomAuth(attrName, ctorArgs, namedArgs));
        }
    }

    private static string GetAttributeArgumentValue(
        AttributeArgumentSyntax arg,
        Compilation compilation,
        List<string> compilationUsings)
    {
        if (arg.Expression is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.StringLiteralExpression))
        {
            return literal.Token.ValueText;
        }

        var exprStr = arg.Expression.ToString();
        if (!string.IsNullOrEmpty(exprStr))
        {
            var resolved = ResolveConst(exprStr, compilationUsings, compilation);
            if (!string.IsNullOrEmpty(resolved))
                return resolved;
        }

        return exprStr;
    }

    private static List<PageRouteQuerystringParameter>? ExtractQueryParams(ImmutableArray<CodeMember> members)
    {
        var queryParams = new List<PageRouteQuerystringParameter>();

        foreach (var member in members)
        {
            if (member.Kind is "property" or "field" &&
                member.AttributeNames.Any(a => a is "SupplyParameterFromQuery" or "SupplyParameterFromQueryAttribute"
                    || a.EndsWith(".SupplyParameterFromQuery") || a.EndsWith(".SupplyParameterFromQueryAttribute")))
            {
                queryParams.Add(new PageRouteQuerystringParameter(member.Name, member.TypeName));
            }
        }

        return queryParams.Count > 0 ? queryParams : null;
    }

    private static List<Invokable>? ExtractInvokables(ImmutableArray<CodeMember> members, string filePath)
    {
        var invokables = new List<Invokable>();
        var className = Path.GetFileNameWithoutExtension(filePath);

        foreach (var member in members)
        {
            if (member.Kind != "method") continue;

            for (int i = 0; i < member.AttributeNames.Length; i++)
            {
                var attrName = member.AttributeNames[i];
                if (!(attrName is "JSInvokable" or "JSInvokableAttribute"
                    || attrName.EndsWith(".JSInvokable") || attrName.EndsWith(".JSInvokableAttribute")))
                    continue;

                var invokableName = ExtractJSInvokableName(member.AttributeTexts[i]);
                invokables.Add(new Invokable($"{className}.{member.Name}", invokableName ?? member.Name));
            }
        }

        return invokables.Count > 0 ? invokables : null;
    }

    private static string? ExtractJSInvokableName(string attrText)
    {
        var parsed = ParseAttributeText(attrText);
        if (parsed?.ArgumentList?.Arguments.Count > 0
            && parsed.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax les
            && les.IsKind(SyntaxKind.StringLiteralExpression)
            && !string.IsNullOrEmpty(les.Token.ValueText))
        {
            return les.Token.ValueText;
        }

        return null;
    }

    private static string ResolveConst(string constName, List<string> namespaceImports, Compilation compilation)
    {
        foreach (var syntaxTree in compilation.SyntaxTrees)
        {
            var semanticModel = compilation.GetSemanticModel(syntaxTree);
            var root = syntaxTree.GetRoot();

            foreach (var fieldDecl in root.DescendantNodes().OfType<FieldDeclarationSyntax>())
            {
                if (!fieldDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.ConstKeyword)))
                    continue;

                foreach (var variable in fieldDecl.Declaration.Variables)
                {
                    var symbol = semanticModel.GetDeclaredSymbol(variable) as IFieldSymbol;
                    if (symbol == null || !symbol.HasConstantValue)
                        continue;

                    if (symbol.Name == constName || symbol.ToDisplayString() == constName)
                    {
                        if (namespaceImports == null || namespaceImports.Count == 0 ||
                            namespaceImports.Contains(symbol.ContainingNamespace.ToDisplayString()))
                        {
                            return symbol.ConstantValue.ToString();
                        }
                    }

                    if (namespaceImports != null)
                    {
                        foreach (var nsImport in namespaceImports)
                        {
                            if (symbol.ToDisplayString().EndsWith($"{nsImport}.{constName}"))
                            {
                                return symbol.ConstantValue.ToString();
                            }
                        }
                    }
                }
            }
        }

        foreach (var assembly in compilation.References
                     .Select(r => compilation.GetAssemblyOrModuleSymbol(r))
                     .OfType<IAssemblySymbol>())
        {
            foreach (var nsImport in namespaceImports ?? [])
            {
                var ns = assembly.GlobalNamespace.GetNamespaceMembers()
                    .FirstOrDefault(n => n.ToDisplayString() == nsImport);
                if (ns == null) continue;

                foreach (var type in ns.GetTypeMembers())
                {
                    foreach (var member in type.GetMembers())
                    {
                        if (member is IFieldSymbol fs && fs.IsConst &&
                            (fs.Name == constName || fs.ToDisplayString() == constName))
                        {
                            return fs.ConstantValue.ToString();
                        }
                    }
                }
            }
        }

        return string.Empty;
    }

    private static List<string> GetCompilationUsings(Compilation compilation)
    {
        var usings = new List<string>();
        foreach (var tree in compilation.SyntaxTrees)
        {
            var root = tree.GetRoot();
            foreach (var usingDirective in root.DescendantNodes().OfType<UsingDirectiveSyntax>())
            {
                var name = usingDirective.Name?.ToString();
                if (!string.IsNullOrEmpty(name) && !usings.Contains(name))
                    usings.Add(name);
            }
        }
        return usings;
    }

    private static string GetClassNameFromContent(string content)
    {
        var match = Regex.Match(content, @"@(?:page|attribute|code|functions|using|inject|layout)\s");
        return match.Success ? "RouteComponent" : Path.GetFileNameWithoutExtension(content);
    }

    private static string ComputeFullSlug(PageRoute pageRoute, Settings settings)
    {
        if (pageRoute.Route == "/" || pageRoute.Route.Length <= 1)
            return "Home";

        var routeTemplate = Routing.TemplateParser.ParseTemplate(pageRoute.Route);
        var nonParamValues = routeTemplate.Segments
            .Where(f => !f.IsParameter)
            .Select(f => f.Value)
            .ToList();

        var fullSlug = Slug.Create(string.Join(".", nonParamValues), new SlugOptions { ToLower = false });
        return string.IsNullOrWhiteSpace(fullSlug) ? pageRoute.Name : fullSlug;
    }

    // ---- Source Generation ----

    private static string BuildSource(Settings settings, List<PageRoute> routes)
    {
        var source = new SourceStringBuilder();

        if (settings.OutputLastCreatedTime)
        {
            source.AppendLine($"// This file was generated on {DateTime.Now:R}");
        }

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#pragma warning disable CS1591");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("using System;");
        source.AppendLine("using System.Net.Http;");
        source.AppendLine("using System.Threading.Tasks;");
        source.AppendLine("using System.Net.Http.Json;");
        source.AppendLine("using System.Collections.Generic;");

        if (settings.OutputIAuthorizeData)
        {
            source.AppendLine("using Microsoft.AspNetCore.Authorization;");
        }

        if (settings.OutputIAuthorizeData || settings.OutputExtensionMethod)
        {
            source.AppendLine("using Microsoft.AspNetCore.Components;");
        }

        source.AppendLine($"namespace {settings.Namespace}");
        source.AppendOpenCurlyBracketLine();
        source.AppendLine($"public static partial class {settings.ClassName}");
        source.AppendOpenCurlyBracketLine();

        if (routes.Count == 0)
        {
            source.AppendCloseCurlyBracketLine();
            source.AppendCloseCurlyBracketLine();
            source.AppendLine("#pragma warning restore CS1591");
            return source.ToString();
        }

        var routeInfos = routes.Select(r => ComputeRouteGenInfo(r, settings)).ToList();

        var completedAuthData = new HashSet<string>();
        var completedConstSlugs = new HashSet<string>();
        var completedBuilderSlugs = new HashSet<string>();

        // F5: Route constants (deduped by slug)
        if (settings.GenerateRouteConstants)
        {
            foreach (var info in routeInfos)
            {
                if (completedConstSlugs.Add(info.FullSlug))
                {
                    source.AppendLine($"public const string {info.FullSlug}_Route = \"{EscapeStringLiteral(info.PageRoute.Route)}\";");
                }
            }
            source.AppendLine();
        }

        if (settings.EnableRouteGrouping)
        {
            // Group routes by their first literal path segment
            var grouped = routeInfos
                .GroupBy(r => r.GroupName ?? string.Empty)
                .ToDictionary(g => g.Key, g => g.ToList());

            // Ungrouped routes (GroupName is empty)
            if (grouped.TryGetValue(string.Empty, out var ungrouped))
            {
                foreach (var info in ungrouped)
                {
                    GenerateRouteContent(source, info, settings, completedAuthData, completedBuilderSlugs, generateExtensions: false);
                }
            }

            // Grouped routes (ordered by group name) — nested static classes
            foreach (var kvp in grouped.Where(g => g.Key != string.Empty).OrderBy(g => g.Key))
            {
                source.AppendLine($"public static class {kvp.Key}");
                source.AppendOpenCurlyBracketLine();

                foreach (var info in kvp.Value)
                {
                    GenerateRouteContent(source, info, settings, completedAuthData, completedBuilderSlugs, generateExtensions: false);
                }

                source.AppendCloseCurlyBracketLine();
            }

            // Close PageRoutes — extension methods go in a separate class to avoid CS0102/CS1109
            source.AppendCloseCurlyBracketLine();

            if (settings.OutputExtensionMethod)
            {
                source.AppendLine($"public static class {settings.ClassName}Extensions");
                source.AppendOpenCurlyBracketLine();

                foreach (var info in routeInfos)
                {
                    AppendExtensionMethod(source, info.FullSlug, info.ParameterString, info.RouteTemplate, info.PageRoute, settings);

                    if (completedAuthData.Add(info.FullSlug))
                    {
                        AppendAuthDataClass(source, info.FullSlug, info.PageRoute, settings);
                    }
                }

                source.AppendCloseCurlyBracketLine();
            }

            // Reopen PageRoutes for remaining members
            source.AppendLine($"public static partial class {settings.ClassName}");
            source.AppendOpenCurlyBracketLine();
        }
        else
        {
            foreach (var info in routeInfos)
            {
                GenerateRouteContent(source, info, settings, completedAuthData, completedBuilderSlugs, generateExtensions: true);
            }
        }

        // F2: Reverse component map
        if (settings.GenerateReverseMap)
        {
            AppendReverseMap(source, routeInfos);
        }

        // F7: TryMatch switch
        if (settings.GenerateTryMatch)
        {
            AppendTryMatch(source, routeInfos);
        }

        source.AppendCloseCurlyBracketLine();
        source.AppendCloseCurlyBracketLine();
        source.AppendLine("#pragma warning restore CS1591");

        return source.ToString();
    }

    private static RouteGenInfo ComputeRouteGenInfo(PageRoute pageRoute, Settings settings)
    {
        var routeTemplate = Routing.TemplateParser.ParseTemplate(pageRoute.Route);

        if (pageRoute.Route == "/" || pageRoute.Route.Length <= 1)
        {
            return new RouteGenInfo(pageRoute, routeTemplate, "Home", "Home", null, "");
        }

        var nonParamValues = routeTemplate.Segments
            .Where(f => !f.IsParameter)
            .Select(f => f.Value)
            .ToList();

        var fullSlug = Slug.Create(string.Join(".", nonParamValues), new SlugOptions { ToLower = false });
        if (string.IsNullOrWhiteSpace(fullSlug))
            fullSlug = pageRoute.Name;

        var parameterString = BuildParameterString(routeTemplate, pageRoute);

        if (!settings.EnableRouteGrouping || nonParamValues.Count == 0)
        {
            return new RouteGenInfo(pageRoute, routeTemplate, fullSlug, fullSlug, null, parameterString);
        }

        // Grouping mode: first literal segment is group name, rest forms method slug
        var firstLiteral = nonParamValues[0];
        var groupName = Slug.Create(firstLiteral, new SlugOptions { ToLower = false });

        var remainingNonParam = nonParamValues.Skip(1).ToList();
        var methodSlug = remainingNonParam.Count > 0
            ? Slug.Create(string.Join(".", remainingNonParam), new SlugOptions { ToLower = false })
            : "Index";

        if (string.IsNullOrWhiteSpace(methodSlug))
            methodSlug = "Index";

        return new RouteGenInfo(pageRoute, routeTemplate, fullSlug, methodSlug, groupName, parameterString);
    }

    private static string BuildParameterString(Routing.RouteTemplate routeTemplate, PageRoute pageRoute)
    {
        var routeSegments = routeTemplate.Segments
            .Where(e => e.IsParameter)
            .Select(segment =>
            {
                var constraint = segment.Constraints.Any()
                    ? segment.Constraints.FirstOrDefault().GetConstraintType()
                    : null;

                if (constraint == null)
                    return $"string {segment.Value}";

                return segment.IsOptional
                    ? $"{constraint.FullName}? {segment.Value}"
                    : $"{constraint.FullName} {segment.Value}";
            }).ToList();

        if (pageRoute.QueryString is { Count: > 0 })
        {
            routeSegments.AddRange(pageRoute.QueryString
                .Select(prqp => $"{prqp.Type} {prqp.Name} = default"));
        }

        return string.Join(", ", routeSegments);
    }

    private static void GenerateRouteContent(SourceStringBuilder source, RouteGenInfo info,
        Settings settings, HashSet<string> completedAuthData, HashSet<string> completedBuilderSlugs,
        bool generateExtensions)
    {
        // Route method
        AppendRouteMethod(source, info.MethodSlug, info.ParameterString, info.RouteTemplate, info.PageRoute, settings);

        // F10: Fluent query builder (deduped by slug)
        if (settings.GenerateFluentBuilder && info.PageRoute.QueryString is { Count: > 0 })
        {
            if (completedBuilderSlugs.Add(info.FullSlug))
            {
                AppendFluentBuilder(source, info.MethodSlug, info.PageRoute);
            }
        }

        // Extension method (only when at top level — never inside nested grouped classes)
        if (generateExtensions && settings.OutputExtensionMethod)
        {
            AppendExtensionMethod(source, info.MethodSlug, info.ParameterString, info.RouteTemplate, info.PageRoute, settings);

            // Auth data class (deduped by FullSlug to avoid duplicates)
            if (completedAuthData.Add(info.FullSlug))
            {
                AppendAuthDataClass(source, info.FullSlug, info.PageRoute, settings);
            }
        }
    }

    private static void AppendRouteMethod(SourceStringBuilder source, string slugName, string parameterString,
        Routing.RouteTemplate routeTemplate, PageRoute pageRoute, Settings settings)
    {
        source.AppendLine($"public static string {slugName} ({parameterString})");
        source.AppendOpenCurlyBracketLine();

        // F4: Validation guard clause placeholder
        if (settings.GenerateValidation && pageRoute.Validations is { Count: > 0 })
        {
            // Validation placeholder - actual rules populated later
        }

        if (routeTemplate.Segments.Any(e => e.IsParameter))
        {
            source.AppendIndent();
            source.Append("string url = $\"", false);
            foreach (var seg in routeTemplate.Segments)
            {
                source.Append(seg.IsParameter ? $"/{{{seg.Value}.ToString()}}" : $"/{seg.Value}", false);
            }
            source.Append("\";\n", false);
        }
        else
        {
            source.AppendLine($"string url = \"{pageRoute.Route}\";");
        }

        if (pageRoute.QueryString is { Count: > 0 })
        {
            source.AppendLine("Dictionary<string, string> queryString=new();");
            foreach (var prqp in pageRoute.QueryString)
            {
                if (prqp.Type == "System.String" || prqp.Type.Equals("string", StringComparison.OrdinalIgnoreCase))
                {
                    source.AppendLine($"if (!string.IsNullOrWhiteSpace({prqp.Name})) ");
                }
                else
                {
                    source.AppendLine($"if ({prqp.Name} != default) ");
                }
                source.AppendOpenCurlyBracketLine();
                source.AppendLine($"queryString.Add(\"{prqp.Name}\", {prqp.Name}.ToString());");
                source.AppendCloseCurlyBracketLine();
            }
            source.AppendLine("");
            source.AppendLine("url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);");
        }

        source.AppendLine("return url;");
        source.AppendCloseCurlyBracketLine();
    }

    private static void AppendFluentBuilder(SourceStringBuilder source, string slugName, PageRoute pageRoute)
    {
        // Query builder class
        source.AppendLine($"public sealed class {slugName}Query");
        source.AppendOpenCurlyBracketLine();

        foreach (var qp in pageRoute.QueryString!)
        {
            source.AppendLine($"public {qp.Type} {qp.Name} {{ get; set; }}");
        }

        source.AppendCloseCurlyBracketLine();

        // Fluent overload
        var queryParamNames = pageRoute.QueryString.Select(q => q.Name).ToList();
        source.AppendLine($"public static string {slugName}(Action<{slugName}Query> configure)");
        source.AppendOpenCurlyBracketLine();
        source.AppendLine($"var q = new {slugName}Query();");
        source.AppendLine("configure(q);");
        source.AppendLine($"return {slugName}({string.Join(", ", queryParamNames.Select(n => $"q.{n}"))});");
        source.AppendCloseCurlyBracketLine();
    }

    private static void AppendExtensionMethod(SourceStringBuilder source, string slugName, string parameterString,
        Routing.RouteTemplate routeTemplate, PageRoute pageRoute, Settings settings)
    {
        if (pageRoute.Auth is { RequiresAuthentication: true })
        {
            source.AppendLine("/// <summary>");
            source.AppendLine($"/// Page Requires Authentication{(pageRoute.Auth.CustomAuth != null ? ", Custom Authentication Provider (CustomAuth)" : "")}");
            if (pageRoute.Auth.Roles is { Count: > 0 })
                source.AppendLine($"/// Roles: {string.Join(", ", pageRoute.Auth.Roles)}");
            if (pageRoute.Auth.Policies is { Count: > 0 })
                source.AppendLine($"/// Policies: {string.Join(", ", pageRoute.Auth.Policies)}");
            if (pageRoute.Auth.CustomAuth != null)
            {
                foreach (var ca in pageRoute.Auth.CustomAuth)
                {
                    source.AppendLine($"/// Custom Authentication ProviderName: {ca.Name}");
                    source.AppendLine($"/// Custom Auth Constructor Params: {string.Join(", ", ca.CtorParams)}");
                    source.AppendLine($"/// Custom Auth Named Params: {string.Join(", ", ca.NamedParams)}");
                }
            }
            source.AppendLine("/// </summary>");
        }

        if (string.IsNullOrWhiteSpace(parameterString))
        {
            source.AppendLine($"public static void {slugName} (this NavigationManager manager, bool forceLoad = false, bool replace=false)");
        }
        else
        {
            source.AppendLine($"public static void {slugName} (this NavigationManager manager, {parameterString}, bool forceLoad = false, bool replace=false)");
        }

        source.AppendOpenCurlyBracketLine();

        if (routeTemplate.Segments.Any(e => e.IsParameter))
        {
            source.AppendIndent();
            source.Append("string url = $\"", false);
            foreach (var seg in routeTemplate.Segments)
            {
                source.Append(seg.IsParameter ? $"/{{{seg.Value}.ToString()}}" : $"/{seg.Value}", false);
            }
            source.Append("\";\n", false);
        }
        else
        {
            source.AppendLine($"string url = \"{pageRoute.Route}\";");
        }

        if (pageRoute.QueryString is { Count: > 0 })
        {
            source.AppendLine("Dictionary<string, string> queryString=new();");
            foreach (var prqp in pageRoute.QueryString)
            {
                if (prqp.Type == "System.String" || prqp.Type.Equals("string", StringComparison.OrdinalIgnoreCase))
                {
                    source.AppendLine($"if (!string.IsNullOrWhiteSpace({prqp.Name})) ");
                }
                else
                {
                    source.AppendLine($"if ({prqp.Name} != default) ");
                }
                source.AppendOpenCurlyBracketLine();
                source.AppendLine($"queryString.Add(\"{prqp.Name}\", {prqp.Name}.ToString());");
                source.AppendCloseCurlyBracketLine();
            }
            source.AppendLine("");
            source.AppendLine("url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);");
        }

        source.AppendLine("manager.NavigateTo(url, forceLoad, replace);");
        source.AppendCloseCurlyBracketLine();
    }

    private static void AppendAuthDataClass(SourceStringBuilder source, string slugName, PageRoute pageRoute, Settings settings)
    {
        if (pageRoute.Auth is not { RequiresAuthentication: true } || !settings.OutputIAuthorizeData)
            return;

        source.AppendLine($"public class {slugName}_AuthData : IAuthorizeData");
        source.AppendOpenCurlyBracketLine();

        if (pageRoute.Auth.CustomAuth is { Count: > 0 })
        {
            var authItem = pageRoute.Auth.CustomAuth.FirstOrDefault();
            var authCfg = settings.Auth.FirstOrDefault(a =>
                a.Attribute != null && a.Attribute.Contains(authItem.Name));

            if (authCfg != null)
            {
                var policyList = EvaluateCode(authCfg.PolicyTransformer, authItem);
                var rolesList = EvaluateCode(authCfg.RolesTransformer, authItem);
                var authSchemesList = EvaluateCode(authCfg.AuthenticationSchemeTransformer, authItem);

                source.AppendLine($"public string Policy {{ get; set; }} = {(policyList?.Count > 0 ? $"\"{string.Join(", ", policyList.Select(QuoteLiteral))}\"" : "String.Empty")}; ");
                source.AppendLine($"public string Roles {{ get; set; }} = {(rolesList?.Count > 0 ? $"\"{string.Join(", ", rolesList.Select(QuoteLiteral))}\"" : "String.Empty")}; ");
                source.AppendLine($"public string AuthenticationSchemes {{ get; set; }} = {(authSchemesList?.Count > 0 ? $"\"{string.Join(", ", authSchemesList.Select(QuoteLiteral))}\"" : "String.Empty")}; ");
            }
        }
        else
        {
            source.AppendLine($"public string Policy {{ get; set; }} = {(pageRoute.Auth.Policies?.Count > 0 ? $"\"{string.Join(",", pageRoute.Auth.Policies)}\"" : "String.Empty")};");
            source.AppendLine($"public string Roles {{ get; set; }} = {(pageRoute.Auth.Roles?.Count > 0 ? $"\"{string.Join(",", pageRoute.Auth.Roles)}\"" : "String.Empty")}; ");
            source.AppendLine($"public string AuthenticationSchemes {{ get; set; }} = {(pageRoute.Auth.AuthenticationSchemes?.Count > 0 ? $"\"{string.Join(", ", pageRoute.Auth.AuthenticationSchemes)}\"" : "String.Empty")}; ");
        }

        source.AppendCloseCurlyBracketLine();
    }

    private static void AppendReverseMap(SourceStringBuilder source, List<RouteGenInfo> routeInfos)
    {
        source.AppendLine("public static System.Type? ResolveComponent(string route)");
        source.AppendOpenCurlyBracketLine();
        source.AppendLine("return route switch");
        source.AppendOpenCurlyBracketLine();

        foreach (var info in routeInfos)
        {
            source.AppendLine($"\"{EscapeStringLiteral(info.PageRoute.Route)}\" => typeof({info.PageRoute.FullTypeName}),");
        }

        source.AppendLine("_ => null");
        source.AppendCloseCurlyBracketLine();
        source.AppendLine(";");
        source.AppendCloseCurlyBracketLine();
        source.AppendLine();
    }

    private static void AppendTryMatch(SourceStringBuilder source, List<RouteGenInfo> routeInfos)
    {
        source.AppendLine("public static bool TryMatch(string path, out string? routeName, out System.Collections.Generic.Dictionary<string, string?>? parameters)");
        source.AppendOpenCurlyBracketLine();
        source.AppendLine("parameters = null;");
        source.AppendLine("switch (path.Trim('/'))");
        source.AppendOpenCurlyBracketLine();

        foreach (var info in routeInfos)
        {
            var routeTemplate = info.RouteTemplate;
            var hasParams = routeTemplate.Segments.Any(s => s.IsParameter);
            var nonParamParts = routeTemplate.Segments
                .TakeWhile(s => !s.IsParameter)
                .Select(s => s.Value)
                .ToList();
            var prefix = string.Join("/", nonParamParts);

            if (hasParams)
            {
                if (nonParamParts.Count > 0)
                {
                    source.AppendLine($"case string p when p.StartsWith(\"{prefix}/\"):");
                }
                else
                {
                    source.AppendLine("case string p:");
                }
            }
            else
            {
                var trimmed = info.PageRoute.Route.Trim('/');
                var caseValue = string.IsNullOrEmpty(trimmed) ? "\"\"" : $"\"{trimmed}\"";
                source.AppendLine($"case {caseValue}:");
            }

            source.AppendLine($"routeName = \"{info.FullSlug}\";");

            if (hasParams)
            {
                var paramSegments = routeTemplate.Segments.Where(s => s.IsParameter).ToList();
                source.AppendLine("parameters = new System.Collections.Generic.Dictionary<string, string?>();");
                if (paramSegments.Count == 1 && nonParamParts.Count > 0)
                {
                    source.AppendLine($"parameters[\"{paramSegments[0].Value}\"] = path.Substring(\"{prefix}/\".Length);");
                }
                else if (paramSegments.Count == 1)
                {
                    source.AppendLine($"parameters[\"{paramSegments[0].Value}\"] = path;");
                }
                else
                {
                    source.AppendLine("var parts = path.Split('/');");
                    for (int i = 0; i < paramSegments.Count; i++)
                    {
                        var seg = paramSegments[i];
                        var nonParamCount = routeTemplate.Segments.TakeWhile(s => !s.IsParameter).Count();
                        var index = nonParamCount + i;
                        source.AppendLine($"parameters[\"{seg.Value}\"] = parts.Length > {index} ? parts[{index}] : null;");
                    }
                }
            }

            source.AppendLine("return true;");
        }

        source.AppendLine("default:");
        source.AppendLine("routeName = null;");
        source.AppendLine("return false;");
        source.AppendCloseCurlyBracketLine();
        source.AppendCloseCurlyBracketLine();
    }

    private static string GenerateHttpFile(List<PageRoute> routes)
    {
        var sb = new StringBuilder();
        foreach (var route in routes)
        {
            var name = route.Name.Replace("_", "-");
            sb.AppendLine($"### {name}");
            sb.AppendLine($"GET {{{{baseUrl}}}}{route.Route}");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    private static void GenerateJSInvokable(Settings settings, List<PageRoute> routes)
    {
        var invokables = routes
            .Where(pr => pr.Invokables != null && pr.Invokables.Any())
            .SelectMany(pr => pr.Invokables)
            .ToList();

        if (invokables.Count == 0) return;

        var jsBuilder = new StringBuilder();
        jsBuilder.AppendLine($"const {settings.Invokables.JSClassName} = {{");

        foreach (var invoke in invokables)
        {
            jsBuilder.AppendLine($"{invoke.InvokableName.Replace(".", "_")}: \"{invoke.MethodName}\", ");
        }

        jsBuilder.AppendLine("};");

        if (settings.Invokables.OutputToFiles.Count > 0)
        {
            foreach (var outputPath in settings.Invokables.OutputToFiles)
            {
                try { File.WriteAllText(outputPath, jsBuilder.ToString()); } catch { }
            }
        }
    }

    private static List<string>? EvaluateCode(string? transformer, PageRouteAuthCustomAuth authItem)
    {
        if (string.IsNullOrWhiteSpace(transformer))
            return null;

        try
        {
            var evaluator = new Data.Eval.Evaluator(transformer);
            evaluator.AddUsing("System.Collections.Generic");
            evaluator["ConstructorParameters"] = authItem.CtorParams;
            evaluator["NamedParameters"] = authItem.NamedParams;
            return evaluator.Eval<List<string>>();
        }
        catch
        {
            return null;
        }
    }

    private static string QuoteLiteral(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string EscapeStringLiteral(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static Dictionary<string, string> ReadRouteCache(string cachePath)
    {
        try
        {
            if (File.Exists(cachePath))
            {
                var json = File.ReadAllText(cachePath);
                return JsonSerializer.Deserialize<Dictionary<string, string>>(json) ?? [];
            }
        }
        catch { }
        return [];
    }

    private static void WriteRouteCache(string cachePath, List<PageRoute> routes, Settings settings)
    {
        try
        {
            var dir = Path.GetDirectoryName(cachePath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            var cache = routes.ToDictionary(
                r => r.Route,
                r => ComputeFullSlug(r, settings));

            var json = JsonSerializer.Serialize(cache, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(cachePath, json);
        }
        catch { }
    }
}

internal record struct GeneratorOptions(string RootNamespace, string BaseIntermediateOutputPath);

internal record struct GenerationResult(
    Settings Settings,
    List<PageRoute> Routes,
    List<(string Route, List<string> FileNames)> Duplicates,
    List<(string Route, string OldMethod, string NewMethod)> RenamedRoutes,
    string? CachePath);

internal record struct RouteGenInfo(
    PageRoute PageRoute,
    Routing.RouteTemplate RouteTemplate,
    string FullSlug,
    string MethodSlug,
    string? GroupName,
    string ParameterString);
