// This file was generated on Sun, 21 Jun 2026 00:14:29 GMT
// <auto-generated/>
#pragma warning disable CS1591
#nullable enable
using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Net.Http.Json;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;

namespace GoLive.Generator.RazorPageRoute.Tests.BlazorWebassembly10
{
    public static partial class PageRoutes
    {
        public const string Counter_Route = "/counter";
        public const string Secure_Route = "/secure";
        public const string Not_Found_Route = "/not-found";
        public const string Home_Route = "/";
        public const string Profile_Route = "/profile";
        public const string Weather_Route = "/weather";
        public const string Admin_Dashboard_Route = "/admin/dashboard";
        public static string Home()
        {
            string url = "/";
            return url;
        }

        public static class Admin
        {
            public static string Dashboard(string Section = default)
            {
                string url = "/admin/dashboard";
                Dictionary<string, string> queryString = new();
                if (!string.IsNullOrWhiteSpace(Section))
                {
                    queryString.Add("Section", Section.ToString());
                }

                url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);
                return url;
            }

            public sealed class DashboardQuery
            {
                public string Section { get; set; }
            }

            public static string Dashboard(Action<DashboardQuery> configure)
            {
                var q = new DashboardQuery();
                configure(q);
                return Dashboard(q.Section);
            }
        }

        public static class Counter
        {
            public static string Index()
            {
                string url = "/counter";
                return url;
            }
        }

        public static class Not_Found
        {
            public static string Index()
            {
                string url = "/not-found";
                return url;
            }
        }

        public static class Profile
        {
            public static string Index(string Name = default, int Age = default)
            {
                string url = "/profile";
                Dictionary<string, string> queryString = new();
                if (!string.IsNullOrWhiteSpace(Name))
                {
                    queryString.Add("Name", Name.ToString());
                }

                if (Age != default)
                {
                    queryString.Add("Age", Age.ToString());
                }

                url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);
                return url;
            }

            public sealed class IndexQuery
            {
                public string Name { get; set; }
                public int Age { get; set; }
            }

            public static string Index(Action<IndexQuery> configure)
            {
                var q = new IndexQuery();
                configure(q);
                return Index(q.Name, q.Age);
            }

            public static string Index(System.Int32 id, string Name = default, int Age = default)
            {
                string url = $"/profile/{id.ToString()}";
                Dictionary<string, string> queryString = new();
                if (!string.IsNullOrWhiteSpace(Name))
                {
                    queryString.Add("Name", Name.ToString());
                }

                if (Age != default)
                {
                    queryString.Add("Age", Age.ToString());
                }

                url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);
                return url;
            }
        }

        public static class Secure
        {
            public static string Index(string ReturnUrl = default)
            {
                string url = "/secure";
                Dictionary<string, string> queryString = new();
                if (!string.IsNullOrWhiteSpace(ReturnUrl))
                {
                    queryString.Add("ReturnUrl", ReturnUrl.ToString());
                }

                url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);
                return url;
            }

            public sealed class IndexQuery
            {
                public string ReturnUrl { get; set; }
            }

            public static string Index(Action<IndexQuery> configure)
            {
                var q = new IndexQuery();
                configure(q);
                return Index(q.ReturnUrl);
            }
        }

        public static class Weather
        {
            public static string Index()
            {
                string url = "/weather";
                return url;
            }
        }
    }

    public static class PageRoutesExtensions
    {
        public static void Counter(this NavigationManager manager, bool forceLoad = false, bool replace = false)
        {
            string url = "/counter";
            manager.NavigateTo(url, forceLoad, replace);
        }

        /// <summary>
        /// Page Requires Authentication
        /// </summary>
        public static void Secure(this NavigationManager manager, string ReturnUrl = default, bool forceLoad = false, bool replace = false)
        {
            string url = "/secure";
            Dictionary<string, string> queryString = new();
            if (!string.IsNullOrWhiteSpace(ReturnUrl))
            {
                queryString.Add("ReturnUrl", ReturnUrl.ToString());
            }

            url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);
            manager.NavigateTo(url, forceLoad, replace);
        }

        public class Secure_AuthData : IAuthorizeData
        {
            public string Policy { get; set; } = String.Empty;
            public string Roles { get; set; } = String.Empty;
            public string AuthenticationSchemes { get; set; } = String.Empty;
        }

        public static void Not_Found(this NavigationManager manager, bool forceLoad = false, bool replace = false)
        {
            string url = "/not-found";
            manager.NavigateTo(url, forceLoad, replace);
        }

        public static void Home(this NavigationManager manager, bool forceLoad = false, bool replace = false)
        {
            string url = "/";
            manager.NavigateTo(url, forceLoad, replace);
        }

        public static void Profile(this NavigationManager manager, string Name = default, int Age = default, bool forceLoad = false, bool replace = false)
        {
            string url = "/profile";
            Dictionary<string, string> queryString = new();
            if (!string.IsNullOrWhiteSpace(Name))
            {
                queryString.Add("Name", Name.ToString());
            }

            if (Age != default)
            {
                queryString.Add("Age", Age.ToString());
            }

            url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);
            manager.NavigateTo(url, forceLoad, replace);
        }

        public static void Profile(this NavigationManager manager, System.Int32 id, string Name = default, int Age = default, bool forceLoad = false, bool replace = false)
        {
            string url = $"/profile/{id.ToString()}";
            Dictionary<string, string> queryString = new();
            if (!string.IsNullOrWhiteSpace(Name))
            {
                queryString.Add("Name", Name.ToString());
            }

            if (Age != default)
            {
                queryString.Add("Age", Age.ToString());
            }

            url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);
            manager.NavigateTo(url, forceLoad, replace);
        }

        public static void Weather(this NavigationManager manager, bool forceLoad = false, bool replace = false)
        {
            string url = "/weather";
            manager.NavigateTo(url, forceLoad, replace);
        }

        /// <summary>
        /// Page Requires Authentication
        /// Roles: admin
        /// </summary>
        public static void Admin_Dashboard(this NavigationManager manager, string Section = default, bool forceLoad = false, bool replace = false)
        {
            string url = "/admin/dashboard";
            Dictionary<string, string> queryString = new();
            if (!string.IsNullOrWhiteSpace(Section))
            {
                queryString.Add("Section", Section.ToString());
            }

            url = Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(url, queryString);
            manager.NavigateTo(url, forceLoad, replace);
        }

        public class Admin_Dashboard_AuthData : IAuthorizeData
        {
            public string Policy { get; set; } = String.Empty;
            public string Roles { get; set; } = "admin";
            public string AuthenticationSchemes { get; set; } = String.Empty;
        }
    }

    public static partial class PageRoutes
    {
        public static System.Type? ResolveComponent(string route)
        {
            return route switch
            {
                "/counter" => typeof(GoLive.Generator.RazorPageRoute.Tests.BlazorWebAssembly10.Pages.Counter),
                "/secure" => typeof(GoLive.Generator.RazorPageRoute.Tests.BlazorWebAssembly10.Pages.SecurePage),
                "/not-found" => typeof(GoLive.Generator.RazorPageRoute.Tests.BlazorWebAssembly10.Pages.NotFound),
                "/" => typeof(GoLive.Generator.RazorPageRoute.Tests.BlazorWebAssembly10.Pages.Home),
                "/profile" => typeof(GoLive.Generator.RazorPageRoute.Tests.BlazorWebAssembly10.Pages.Profile),
                "/profile/{id:int}" => typeof(GoLive.Generator.RazorPageRoute.Tests.BlazorWebAssembly10.Pages.Profile),
                "/weather" => typeof(GoLive.Generator.RazorPageRoute.Tests.BlazorWebAssembly10.Pages.Weather),
                "/admin/dashboard" => typeof(GoLive.Generator.RazorPageRoute.Tests.BlazorWebAssembly10.Pages.Admin),
                _ => null
            };
        }

        public static bool TryMatch(string path, out string? routeName, out System.Collections.Generic.Dictionary<string, string?>? parameters)
        {
            parameters = null;
            switch (path.Trim('/'))
            {
                case "counter":
                    routeName = "Counter";
                    return true;
                case "secure":
                    routeName = "Secure";
                    return true;
                case "not-found":
                    routeName = "Not_Found";
                    return true;
                case "":
                    routeName = "Home";
                    return true;
                case "profile":
                    routeName = "Profile";
                    return true;
                case string p when p.StartsWith("profile/"):
                    routeName = "Profile";
                    parameters = new System.Collections.Generic.Dictionary<string, string?>();
                    parameters["id"] = path.Substring("profile/".Length);
                    return true;
                case "weather":
                    routeName = "Weather";
                    return true;
                case "admin/dashboard":
                    routeName = "Admin_Dashboard";
                    return true;
                default:
                    routeName = null;
                    return false;
            }
        }
    }
}
#pragma warning restore CS1591
