### Counter
GET {{baseUrl}}/counter

### SecurePage
GET {{baseUrl}}/secure

### NotFound
GET {{baseUrl}}/not-found

### Home
GET {{baseUrl}}/

### Profile
GET {{baseUrl}}/profile

### Profile
GET {{baseUrl}}/profile/{id:int}

### Weather
GET {{baseUrl}}/weather

### Admin
GET {{baseUrl}}/admin/dashboard

