<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>GoLive.Generator.RazorPageRoute.Generator.Tests</RootNamespace>
        <AssemblyName>GoLive.Generator.RazorPageRoute.Generator.Tests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="System.Text.Json" Version="9.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GoLive.Generator.RazorPageRoute.Generator\GoLive.Generator.RazorPageRoute.Generator.csproj" />
        <ProjectReference Include="..\GoLive.Generator.RazorPageRoute.Generator.Experimental\GoLive.Generator.RazorPageRoute.Generator.Experimental.csproj" />
    </ItemGroup>

</Project>
