name: Publish Experimental
on:
  workflow_dispatch:

jobs:
  publish:
    env:
     MainProject: 'GoLive.Generator.RazorPageRoute.Generator/GoLive.Generator.RazorPageRoute.Generator.csproj'
     ExperimentalProject: 'GoLive.Generator.RazorPageRoute.Generator.Experimental/GoLive.Generator.RazorPageRoute.Generator.Experimental.csproj'
     AnalyzerProject: 'GoLive.Generator.RazorPageRoute.Analyzer/GoLive.Generator.RazorPageRoute.Analyzer.csproj'
     BUILD_VER : '2.3'
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{secrets.NUGET_KEY}}
      - name: Get Build Version
        run: |
          echo "BUILD_VERSION=${{ format('{0}.{1}', env.BUILD_VER, github.run_number ) }}-alpha" >> $env:GITHUB_ENV
      - name: Build Main
        run: dotnet pack $env:MainProject --configuration Release -p:Version=$env:BUILD_VERSION -p:PackageVersion=$env:BUILD_VERSION -p:GeneratePackageOnBuild=false
      - name: Build Experimental
        run: dotnet pack $env:ExperimentalProject --configuration Release -p:Version=$env:BUILD_VERSION -p:PackageVersion=$env:BUILD_VERSION -p:GeneratePackageOnBuild=false
      - name: Build Analyzer
        run: dotnet pack $env:AnalyzerProject --configuration Release -p:Version=$env:BUILD_VERSION -p:PackageVersion=$env:BUILD_VERSION -p:GeneratePackageOnBuild=false
      - name: Publish
        run: nuget push **/*.nupkg -Source 'https://api.nuget.org/v3/index.json' 