name: Publish Experimental
on:
  workflow_dispatch:

jobs:
  publish:
    env:
     MainProject: 'GoLive.Generator.RazorPageRoute.Generator/GoLive.Generator.RazorPageRoute.Generator.csproj'
     BUILD_VER : '2.0'
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
      - name: Get Build Version
        run: |
          echo "BUILD_VERSION=${{ format('{0}.{1}', env.BUILD_VER, github.run_number ) }}-alpha" >> $GITHUB_ENV
      - name: Build Main 
        run: dotnet pack $MainProject --configuration Release -p:Version=$BUILD_VERSION -p:PackageVersion=$BUILD_VERSION -p:NuGetVersion=$BUILD_VERSION -p:GeneratePackageOnBuild=false
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_KEY}}